LANDMARK_NAMES = [
    'contour_chin', 
    'contour_left1', 
    'contour_left3', 
    'contour_left5', 
    'contour_left7', 
    'contour_left9', 
    'contour_right1', 
    'contour_right3', 
    'contour_right5', 
    'contour_right7', 
    'contour_right9', 

    'left_eye_bottom', 
    'left_eye_left_corner', 
    'left_eye_right_corner', 
    'left_eye_top', 
    'left_eyebrow_right_corner', 
    'left_eyebrow_upper_left_quarter', 
    'left_eyebrow_upper_middle', 
    'left_eyebrow_upper_right_quarter', 
    
    'mouth_left_corner', 'mouth_lower_lip_bottom', 
    'mouth_lower_lip_left_contour2', 
    'mouth_lower_lip_left_contour3', 
    'mouth_lower_lip_right_contour2', 
    'mouth_lower_lip_right_contour3', 
    'mouth_right_corner', 
    'mouth_upper_lip_left_contour1', 
    'mouth_upper_lip_left_contour2', 
    'mouth_upper_lip_right_contour1', 
    'mouth_upper_lip_right_contour2', 
    'mouth_upper_lip_top', 
    
    'nose_contour_left1', 
    'nose_contour_left2', 
    'nose_contour_left3', 
    'nose_contour_lower_middle', 
    'nose_contour_right1', 
    'nose_contour_right2', 
    'nose_contour_right3', 
    'nose_left', 
    'nose_right', 
    'nose_tip', 
    
    'right_eye_bottom', 
    'right_eye_left_corner', 
    'right_eye_right_corner', 
    'right_eye_top', 
    'right_eyebrow_left_corner', 
    'right_eyebrow_upper_left_quarter', 
    'right_eyebrow_upper_middle', 
    'right_eyebrow_upper_right_quarter', 

    'lt', 'rt', 'lb', 'rb'
]

TARGET2_LANDMARKS = {
    'contour_chin':{'x': 162, 'y': 428}, 
    'contour_left1':{'x': 7, 'y': 173}, 
    'contour_left3':{'x': 19, 'y': 269}, 
    'contour_left5':{'x': 65, 'y': 364}, 
    'contour_left7':{'x': 102, 'y': 403}, 
    'contour_left9':{'x': 129, 'y': 427}, 
    'contour_right1':{'x': 275, 'y': 152}, 
    'contour_right3':{'x': 259, 'y': 258}, 
    'contour_right5':{'x': 247, 'y': 353}, 
    'contour_right7':{'x': 227, 'y': 390}, 
    'contour_right9':{'x': 199, 'y': 420}, 
    
    'left_eye_bottom':{'x': 63, 'y': 171}, 
    'left_eye_left_corner':{'x': 39, 'y': 157}, 
    'left_eye_right_corner':{'x': 83, 'y': 156}, 
    'left_eye_top':{'x': 65, 'y': 139}, 
    'left_eyebrow_right_corner':{'x': 94, 'y': 140}, 
    'left_eyebrow_upper_left_quarter':{'x': 31, 'y': 138}, 
    'left_eyebrow_upper_middle':{'x': 51, 'y': 128}, 
    'left_eyebrow_upper_right_quarter':{'x': 78, 'y': 127}, 
    
    'mouth_left_corner':{'x': 96, 'y': 375}, 
    'mouth_lower_lip_bottom':{'x': 161, 'y': 364}, 
    'mouth_lower_lip_left_contour2':{'x': 115, 'y': 389}, 
    'mouth_lower_lip_left_contour3':{'x': 135, 'y': 371}, 
    'mouth_lower_lip_right_contour2':{'x': 213, 'y': 385}, 
    'mouth_lower_lip_right_contour3':{'x': 193, 'y': 371}, 
    'mouth_right_corner':{'x': 234, 'y': 359}, 
    'mouth_upper_lip_left_contour1':{'x': 140, 'y': 345}, 
    'mouth_upper_lip_left_contour2':{'x': 122, 'y': 364}, 
    'mouth_upper_lip_right_contour1':{'x': 182, 'y': 344}, 
    'mouth_upper_lip_right_contour2':{'x': 213, 'y': 355}, 
    'mouth_upper_lip_top':{'x': 158, 'y': 335}, 
    
    'nose_contour_left1':{'x': 111, 'y': 198}, 
    'nose_contour_left2':{'x': 107, 'y': 245}, 
    'nose_contour_left3':{'x': 126, 'y': 298}, 
    'nose_contour_lower_middle':{'x': 155, 'y': 314}, 
    'nose_contour_right1':{'x': 170, 'y': 199}, 
    'nose_contour_right2':{'x': 186, 'y': 237}, 
    'nose_contour_right3':{'x': 177, 'y': 293}, 
    'nose_left':{'x': 94, 'y': 277}, 
    'nose_right':{'x': 202, 'y': 266}, 
    'nose_tip':{'x': 149, 'y': 271}, 
    
    'right_eye_bottom':{'x': 208, 'y': 157}, 
    'right_eye_left_corner':{'x': 191, 'y': 147}, 
    'right_eye_right_corner':{'x': 230, 'y': 141}, 
    'right_eye_top':{'x': 203, 'y': 129}, 
    'right_eyebrow_left_corner':{'x': 183, 'y': 131}, 
    'right_eyebrow_upper_left_quarter':{'x': 204, 'y': 116}, 
    'right_eyebrow_upper_middle':{'x': 223, 'y': 119}, 
    'right_eyebrow_upper_right_quarter':{'x': 245, 'y': 131}, 
}